export type TourPlacement = 'top' | 'bottom' | 'auto';

export interface TourStep {
  id: string;
  target: string;
  route: string;
  section: string;
  title: string;
  description: string;
  placement?: TourPlacement;
  spotlightPadding?: number;
  spotlightRadius?: number;
  showSpotlightBorder?: boolean;
}

/**
 * The tour follows the primary operating journey rather than the route map:
 * understand the current position, record activity, review it, set limits,
 * analyse results, then plan what comes next.
 *
 * Targets intentionally identify stable feature regions instead of individual
 * implementation details so the tour remains useful as each screen evolves.
 */
export const TOUR_STEPS: TourStep[] = [
  {
    id: 'home-period',
    target: '[data-tour-id="home-period"]',
    route: '/',
    section: 'Home',
    title: 'Period and spending view',
    description: 'Move between months and switch between Actual spending and Net, which excludes one-off Extra transactions.',
    placement: 'bottom',
  },
  {
    id: 'safe-to-spend',
    target: '[data-tour-id="safe-to-spend"]',
    route: '/',
    section: 'Home',
    title: 'Available to Spend',
    description: 'Your remaining monthly spending power. Open this summary to go directly to category budgets.',
    placement: 'bottom',
  },
  {
    id: 'home-monthly-summary',
    target: '[data-tour-id="home-monthly-summary"]',
    route: '/',
    section: 'Home',
    title: 'Monthly totals',
    description: 'Income and spending update for the selected month. Tap either total to open the matching transactions.',
    placement: 'auto',
  },
  {
    id: 'home-cash-flow',
    target: '[data-tour-id="home-cash-flow"]',
    route: '/',
    section: 'Home',
    title: 'Cash-flow preview',
    description: 'See how income, expenses, and net cash flow are evolving, then open the full report for deeper analysis.',
    placement: 'auto',
  },
  {
    id: 'home-recent',
    target: '[data-tour-id="home-recent"]',
    route: '/',
    section: 'Home',
    title: 'Recent transactions',
    description: 'Review the latest activity. Tap a row for details, then use Edit to open the complete transaction form.',
    placement: 'top',
  },
  {
    id: 'primary-navigation',
    target: '[data-tour-id="primary-navigation"]',
    route: '/',
    section: 'Navigation',
    title: 'Primary navigation',
    description: 'Move between Home, Transactions, Budgets, and Reports. The raised centre action always starts a new transaction.',
    placement: 'top',
    spotlightPadding: 0,
    spotlightRadius: 0,
    showSpotlightBorder: false,
  },
  {
    id: 'add-entry',
    target: '[data-tour-id="add-entry"]',
    route: '/add',
    section: 'Add transaction',
    title: 'Type and amount',
    description: 'Choose Expense or Income, then tap the amount to use the numeric keypad.',
    placement: 'bottom',
  },
  {
    id: 'add-details',
    target: '[data-tour-id="add-details"]',
    route: '/add',
    section: 'Add transaction',
    title: 'Essential details',
    description: 'Give the transaction a clear title, choose its category, and set the effective date.',
    placement: 'auto',
  },
  {
    id: 'reporting-treatment',
    target: '[data-tour-id="reporting-treatment"]',
    route: '/add',
    section: 'Add transaction',
    title: 'Extra and Refund treatment',
    description: 'Mark exceptional expenses as Extra or incoming reimbursements as Refund so Net reporting stays meaningful.',
    placement: 'auto',
  },
  {
    id: 'add-more-options',
    target: '[data-tour-id="add-more-options"]',
    route: '/add',
    section: 'Add transaction',
    title: 'Optional details',
    description: 'Expand More options to add a payment method, notes, or a receipt without crowding the everyday flow.',
    placement: 'top',
  },
  {
    id: 'history-controls',
    target: '[data-tour-id="history-controls"]',
    route: '/transactions',
    section: 'Transactions',
    title: 'Search, filter, and sort',
    description: 'Search instantly, limit the list by type, and open Filters for categories, periods, and ordering.',
    placement: 'bottom',
  },
  {
    id: 'history-list',
    target: '[data-tour-id="history-list"]',
    route: '/transactions',
    section: 'Transactions',
    title: 'Transaction history',
    description: 'Transactions are grouped by date. Tap for full details, or swipe a row to edit or delete it quickly.',
    placement: 'auto',
  },
  {
    id: 'budget-summary',
    target: '[data-tour-id="budget-summary"]',
    route: '/budgets',
    section: 'Budgets',
    title: 'Monthly budget health',
    description: 'Track total limits, spending, remaining budget, and Safe to Spend for the selected analytics view.',
    placement: 'bottom',
  },
  {
    id: 'budget-categories',
    target: '[data-tour-id="budget-categories"]',
    route: '/budgets',
    section: 'Budgets',
    title: 'Category limits',
    description: 'Add or edit limits and use each progress bar to spot categories that are close to or over budget.',
    placement: 'auto',
  },
  {
    id: 'reports-navigation',
    target: '[data-tour-id="reports-navigation"]',
    route: '/reports',
    section: 'Reports',
    title: 'Report views',
    description: 'Switch between Overview, category breakdowns, period comparisons, and the annual review.',
    placement: 'bottom',
  },
  {
    id: 'reports-options',
    target: '[data-tour-id="reports-options"]',
    route: '/reports',
    section: 'Reports',
    title: 'Report scope',
    description: 'View options controls whether reports include all spending, exclude Extras, or show Extras only.',
    placement: 'bottom',
  },
  {
    id: 'reports-overview-summary',
    target: '[data-tour-id="reports-overview-summary"], [data-tour-id="reports-empty"]',
    route: '/reports',
    section: 'Reports overview',
    title: 'Overview total',
    description: 'Choose a period and compare its total spending with the preceding equivalent period.',
    placement: 'auto',
  },
  {
    id: 'reports-spending-pace',
    target: '[data-tour-id="reports-spending-pace"], [data-tour-id="reports-empty"]',
    route: '/reports',
    section: 'Reports overview',
    title: 'Spending pace',
    description: 'Compare your current daily, weekly, and monthly spending rate. Open the trend to switch scale and inspect the rolling averages over time.',
    placement: 'auto',
  },
  {
    id: 'reports-overview-chart',
    target: '[data-tour-id="reports-overview-chart"], [data-tour-id="reports-empty"]',
    route: '/reports',
    section: 'Reports overview',
    title: 'Income, expenses, and net flow',
    description: 'The combined chart shows income and expenses as bars and net cash flow as a line; the comparison below isolates the change in net flow.',
    placement: 'auto',
  },
  {
    id: 'reports-categories',
    target: '[data-tour-id="reports-categories"]',
    route: '/reports/categories',
    section: 'Categories report',
    title: 'Spending by category',
    description: 'See categories ranked by amount and share of total spending. Open a category to view its matching transactions for the selected period.',
    placement: 'auto',
  },
  {
    id: 'reports-compare',
    target: '[data-tour-id="reports-compare"]',
    route: '/reports/compare',
    section: 'Compare report',
    title: 'Compare periods and trends',
    description: 'Compare current and previous spending totals, drill into category trends, or use the merchant comparison for a more detailed view.',
    placement: 'auto',
  },
  {
    id: 'reports-year',
    target: '[data-tour-id="reports-year"]',
    route: '/reports/year',
    section: 'Year report',
    title: 'Year in Review',
    description: 'Move between years to review annual totals, highlights, monthly trends, spending intensity, category shifts, and a shareable summary.',
    placement: 'auto',
  },
  {
    id: 'topbar-actions',
    target: '[data-tour-id="topbar-actions"]',
    route: '/',
    section: 'Global tools',
    title: 'Search, alerts, and tools',
    description: 'Search across your workspace, review local alerts, install the app when supported, or open secondary tools from the More menu.',
    placement: 'bottom',
    spotlightPadding: 4,
    spotlightRadius: 999,
  },
  {
    id: 'more-tools',
    target: '[data-tour-id="more-tools"]',
    route: '/more',
    section: 'More',
    title: 'Tools and settings',
    description: 'Open Planning, local-first Data & Privacy controls for backups and archives, or Settings for budgets, categories, notifications, goals, and appearance.',
    placement: 'auto',
  },
  {
    id: 'planning-tabs',
    target: '[data-tour-id="planning-tabs"]',
    route: '/planning',
    section: 'Planning',
    title: 'Calendar and recurring views',
    description: 'Use Calendar to see scheduled activity by date, or Recurring to manage repeating bills and income.',
    placement: 'bottom',
  },
  {
    id: 'planning-summary',
    target: '[data-tour-id="planning-summary"]',
    route: '/planning',
    section: 'Planning',
    title: 'Upcoming commitments',
    description: 'See the scheduled total, number of recurring payments, and the next commitment for the selected month.',
    placement: 'auto',
  },
  {
    id: 'planning-calendar',
    target: '[data-tour-id="planning-calendar"]',
    route: '/planning',
    section: 'Planning',
    title: 'Financial calendar',
    description: 'Select a date to inspect its transactions and recurring items, or add a recurring entry for future months.',
    placement: 'top',
  },
];
